### ISSUE TITLE
Text Editor does not show on edit page when attribute Catalog Input Type for Store Owner is changed to Text Editor.

### ISSUE THREAD

**Issue by cdbessig** [magento/magento2-page-builder#789] opened 2021-10-20 12:35 UTC
### Preconditions (*)
1. Magento 2.4.3 / php 7.4
2. Page Builder 2.2.1

### Steps to reproduce (*)
1.  Add a category attribute with the attribute code "short_description" to your magento install.
2.  Stores->attributes->products, edit short_description to be "text editor" on the "Catalog Input Type for Store Owner"

### Expected result (*)
1. The expected result is that when you go to catalog->products and edit a product, that the short description would show a tinymce editor. 

### Actual result (*)
1. It does not show a tinymce editor.

It seems that the issue is the somewhere page builder is assuming the attribute_code, "short description" is unique.  But attribute code is not unique, the key on the database is (attribute_code, entitiy_type_id) - meaning it is possible to have the same attribute code for products and then for categories.

For anyone having issues like this, the current work around is to rename the attribute code for the category from "short_description" to "short_description_category"

However, this is a bug, because the system should work with the expected result.

**Comment by engcom-Bravo** [comment] 2024-05-10 12:41
Hi @cdbessig,

Thanks for your reporting and collaboration.

We have verified the issue and the issue is no more reproducible.

<img width="1512" alt="Screenshot 2024-05-10 at 2 47 58 PM" src="https://github.com/magento/magento2-page-builder/assets/51680745/635f0683-88a3-470d-97b1-c1b77f92f106">

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-05-10 12:41 UTC
Labels: Progress: done
